Algoritmo "ConversaoDolar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Julia Garcia Mota
// Data atual  : 07/04/2021
Var
cotacao, valor, result: real

Inicio
// ENTRADA
escreval ("Escreva o valor da cotacao do dolar")
leia (cotacao)
escreval ("valor convertido")
leia (valor)

// EXECUCAO
result<- valor/cotacao
//SAIDA
escreval (valor, "reais e o mesmo que", result)

Fimalgoritmo