Algoritmo "PAROUIMPAR SE"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cinthia Pinho
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Julia Garcia Mota
// Data atual  : 07/06/2021
Var
num: inteiro


Inicio
// ENTRADA
escreval ("Digite um numero ")
leia (num)

se (num mod 2)= 0 entao
   escreval ("O numero é par")
senao
   escreval ("O numero é impar")
fimse





Fimalgoritmo