Algoritmo "Continua"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Julia Garcia Mota
// Data atual  : 24/08/2021
Var
soma, num: inteiro


Inicio
num <- 1
 soma <- 0
 enquanto num <> 0 faca
 escreval("Digite um numero:")
 escreval ("Quando quiser saber o resulado digite 0")
 leia(num)
 soma <- soma + num
 fimenquanto
 escreval("O resultado da soma dos numeros digitados é: ", soma)


Fimalgoritmo